version: '3.9'

services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoapp
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

    restart: always
